[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool]
[tool.poetry]
package-mode = false
[tool.poetry.dependencies]
pulumi = ">=3.0.0,<4.0.0"
pulumi-aws = ">=6.0.2,<7.0.0"
pulumi-awsx = ">=2.0.0,<3.0.0"
pulumi-eks = ">=2.0.0,<3.0.0"
python = "^3.8"
